.\" Manpage for jetrunner.
.\" Contact pete.romano@yahoo.com to correct errors or typos.
.TH man 1 "21 September 2012" "0.1.0" "jetrunner man page"
.SH NAME
jetrunner \- binary into jetrunner unit test server
.SH SYNOPSIS
jetrunner [TASK]
.SH DESCRIPTION
jetrunner(1) is a unit test server for the purposes of acting as a multi-purpose test runner, mainly with integration with the jetfuel(1) engine, but may be used stand-alone.
.SH OPTIONS
TBD
.SH SEE ALSO
jetfuel(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Pete Romano (pete.romano@yahoo.com)